# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Diagnosix' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftSiriWaveformView'
  # Pods for Diagnosix

  target 'DiagnosixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiagnosixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
